export const AuthConstants = {
    SIGNIN_REQUEST: 'USERS_SIGNIN_REQUEST',
    SIGNIN_SUCCESS: 'USERS_SIGNIN_SUCCESS',
    SIGNIN_FAILURE: 'USERS_SIGNIN_FAILURE',
  
    SIGNOUT_REQUEST: 'SIGNOUT_REQUEST',
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',
  };
  